Repository cordada/lib-pe-sunat-python, pull requests merged in 2023-09, with the labels that each got.

#125 Update each Python Version for GitHub Actions
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
Labels: dependencies, task

#126 Update pip-tools from 6.14.0 to 7.3.0
  Makefile
  make/python.mk
  requirements-dev.in
  requirements-dev.txt
Labels: dependencies, task

#132 Add dependency groups to Dependabot configuration
  .github/dependabot.yml
Labels: task

#135 Release v1.3.2
  CHANGELOG.md
  cordada/pe_sunat/__init__.py
Labels: task, kind: release

#136 Deploy release v1.3.2
  .github/dependabot.yml
  .github/workflows/ci.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
  CHANGELOG.md
  Makefile
  cordada/pe_sunat/__init__.py
  make/python.mk
  requirements-dev.in
  requirements-dev.txt
  requirements.txt
Labels: task, kind: deploy

#137 Add missing blank line between sections to changelog
  CHANGELOG.md
Labels: bug, documentation

#138 Add Codecov repository upload token to CI/CD
  .github/workflows/ci-cd.yaml
  .github/workflows/ci.yaml
Labels: task
